FROM lucazulberti/workenv:latest

# Go back to root user
USER root

# Override the UID and GID of the non-root user
ARG HOST_UID=1000
ARG HOST_GID=1000
RUN groupmod -g $HOST_GID ubuntu && \
    usermod -u $HOST_UID ubuntu

# Switch to non-root user again
USER ubuntu
